### ISSUE TITLE
The playlist Pluto TV not work

### ISSUE THREAD

**Issue by wuniversales** [EdenwareApps/Megacubo#40]
However, in other players it works.
`https://i.mjh.nz/PlutoTV/all.m3u8`

**Comment by efoxbr** [comment]
Hi @wuniversales, thank you for providing the link for testing. Bug identified and fixed starting from version 17.3.3.

**Comment by EdenwareApps** [comment]
@wuniversales, thanks for reporting it. Bugs that were affecting the Pluto TV listing have been fixed in [version 17.3.6](https://github.com/EdenwareApps/Megacubo/releases/latest). Any problem, please let us know.
