### ISSUE TITLE
Bad test result on error 404/500

### ISSUE THREAD

**Issue by faveoled** [EdenwareApps/Megacubo#41]
Hello. Very nice app. Found 1 issue though:

Sometimes the test result is green but the stream still doesn't work. Redoing the test doesn't make the test result red.
![Screenshot from 2024-01-04 17-02-52](https://github.com/EdenwareApps/Megacubo/assets/85760289/613c0251-9a47-470c-ad19-c8075399fa63)
![Screenshot from 2024-01-04 17-03-01](https://github.com/EdenwareApps/Megacubo/assets/85760289/c85e34d4-c668-470d-a4aa-f1996d8ec939)

Seems to happen on 404/500 errors

**Comment by EdenwareApps** [comment]
Hi @faveoled, thanks for reporting. Could you test again with [version 17.3.6](https://github.com/EdenwareApps/Megacubo/releases/latest) to confirm if the issue is resolved?

**Comment by faveoled** [comment]
Hi. No, I don't see any difference. I'm using Free-TV/IPTV channel list btw

**Comment by EdenwareApps** [comment]
Update to [version 17.4.5](https://github.com/EdenwareApps/Megacubo/releases/tag/v17.4.5) and, to resolve, click Options > Advanced > Tuning > "Skip checking before opening content directly" > Never.
