### ISSUE TITLE
Please Add MAG device support :)

### ISSUE THREAD

**Issue by 99bobster99** [EdenwareApps/Megacubo#47]
Hello,

Please add MAG support, I love your program and I think adding the option to use MAG addresses would be a great addition!

**Comment by EdenwareApps** [comment]
Hello @99bobster99, I worked on MAG support at the request of another user and the access worked for him. Support is implemented from version 17.4.0.

Try updating to the latest version and adding the MAC address in My Lists > Add list > Add with MAC address.

If some error occurs, please let us know what the error message was or send us a screenshot of it.

**Comment by 99bobster99** [comment]
Hello @EdenwareApps, thank you so much for pointing this out. I was use to the way apps like IPTV Smarters enters the MAG information. The way you are doing it is much easier, once you pointed it out.

When using the MAG option, I noticed that the "What do you wanna watch?" search field, at the top of the home page, is missing. Could this be added back in, so that we can search the full index of the IPTV service provider?

I'd also like to contribute, but I'm running into issues when using WebStorm to open your source code. I've loaded Nodejs and ran "git clone https://github.com/EdenwareApps/Megacubo.git", "cd Megacubo", "npm ci" and "npm run debug". All these commands execute successfully, other than the "npm run debug" command. for this command, I'm receiving the following error popup below. What am I doing wrong? 

![image](https://github.com/EdenwareApps/Megacubo/assets/37968888/46739e52-ded5-4e59-b974-9d19e80058ba)

**Comment by EdenwareApps** [comment]
@99bobster99 EPG support for MAG lists was added in [version 17.4.5](https://github.com/EdenwareApps/Megacubo/releases/tag/v17.4.5).

In this version it is also possible to choose an external player by clicking on "Customize" in the external player section dialog or on Options > Advanced > Playback > Choose external player > Customize.

This bug about the search field has also been fixed.

As for this jQuery related error, it doesn't occur here (using NPM directly on Windows).

The error indicates that node_modules/jquery/dist/jquery.min.js was not loaded in index.html or loaded after assets/js/app/index.js.

You can press Ctrl+Shift+i (or F12) to open DevTools for more details about jquery.js loading in the index.html frame. If you (or someone with the same problem) does this and gets more details, please let me know.
