### ISSUE TITLE
probleme last version megacubo 17.4.0 and 17.4.1 and 17.4.2  on linux

### ISSUE THREAD

**Issue by koriko007** [EdenwareApps/Megacubo#51]
Problem with the latest version megacubo 17.4.0 and 17.4.1 and 17.4.2  on linux
When you choose a channel, I then change to another channel, giving me the channel that I watched before

**Comment by EdenwareApps** [comment]
Fixed in [version 17.4.5](https://github.com/EdenwareApps/Megacubo/releases/tag/v17.4.5).
