### ISSUE TITLE
Enhancement: Please add a controller support for the menu

### ISSUE THREAD

**Issue by CartltonCrazeIsBackIGuess** [EdenwareApps/Megacubo#67]
I like using Kodi because it supports controllers, but the recording feature is annoying. I like this software, but it's hard to use when far from the computer. Please add it through Xinput.

**Comment by EdenwareApps** [comment]
Thanks for the suggestion @CartltonCrazeIsBackIGuess, Xinput support (via Gamepad API) will be implemented from version 17.5.1 which will be released in the next few days.
