### ISSUE TITLE
getting issue on npm i

### ISSUE THREAD

**Issue by kutanoor** [EdenwareApps/Megacubo#70]
Please add how to build instructions

npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: undefined@undefined
npm ERR! Found: @capacitor/core@6.1.2
npm ERR! node_modules/@capacitor/core
npm ERR!   @capacitor/core@"^6.1.2" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @capacitor/core@"^5.0.0" from @eoscz/capacitor-plugin-native-file-downloader@2.0.1
npm ERR! node_modules/@eoscz/capacitor-plugin-native-file-downloader
npm ERR!   @eoscz/capacitor-plugin-native-file-downloader@"^2.0.1" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR!
npm ERR! For a full report see:
npm ERR! C:\Users\Manjushri\AppData\Local\npm-cache\_logs\2024-09-07T08_21_51_994Z-eresolve-report.txt

npm ERR! A complete log of this run can be found in: C:\Users\Manjushri\AppData\Local\npm-cache\_logs\2024-09-07T08_21_51_994Z-debug-0.log

**Comment by EdenwareApps** [comment]
Hi @kutanoor, I improved the visibility of the link with the build instructions in the description (commit 14fb921).

https://github.com/EdenwareApps/Megacubo/blob/master/DEVELOPING.md

I also adjusted the project to no longer require the '--force' parameter in the 'npm i' command, which was what caused this error.

**Comment by kutanoor** [comment]
Can you please send me .env file?
