### ISSUE TITLE
Ubuntu

### ISSUE THREAD

**Issue by basimamata** [EdenwareApps/Megacubo#71]
/opt/megacubo/megacubo
[20795:0916/085045.243909:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/megacubo/chrome-sandbox is owned by root and has mode 4755.

**Comment by basimamata** [comment]
ls -la /opt/megacubo/
общо 177012
drwxr-xr-x 6 root root      4096 сеп 16 08:48 .
drwxr-xr-x 4 root root      4096 сеп 16 08:48 ..
-rwxr-xr-x 1 root root    179981 сеп 16 08:48 chrome_100_percent.pak
-rwxr-xr-x 1 root root    321151 сеп 16 08:48 chrome_200_percent.pak
-rwxr-xr-x 1 root root   6322384 сеп 16 08:48 chrome-sandbox
-rwxr-xr-x 1 root root  10505952 сеп 16 08:48 icudtl.dat
-rwxr-xr-x 1 root root      1591 сеп 16 08:48 install.sh
-rwxr-xr-x 1 root root    243896 сеп 16 08:48 libEGL.so
-rwxr-xr-x 1 root root   4305656 сеп 16 08:48 libffmpeg.so
-rwxr-xr-x 1 root root   8944664 сеп 16 08:48 libGLESv2.so
-rwxr-xr-x 1 root root   4486592 сеп 16 08:48 libvk_swiftshader.so
-rwxr-xr-x 1 root root   8483672 сеп 16 08:48 libvulkan.so
drwxr-xr-x 2 root root      4096 сеп 16 08:48 license
-rwxr-xr-x 1 root root   4818222 сеп 16 08:48 LICENSES.chromium.html
drwxr-xr-x 2 root root      4096 сеп 16 08:48 locales
-rwxr-xr-x 1 root root 127524824 сеп 16 08:48 megacubo
-rwxr-xr-x 1 root root       171 сеп 16 08:48 megacubo-debug.sh
drwxr-xr-x 3 root root      4096 сеп 16 08:48 resources
-rwxr-xr-x 1 root root   4836151 сеп 16 08:48 resources.pak
-rwxr-xr-x 1 root root     50592 сеп 16 08:48 snapshot_blob.bin
drwxr-xr-x 2 root root      4096 сеп 16 08:48 swiftshader
-rwxr-xr-x 1 root root    170903 сеп 16 08:48 v8_context_snapshot.bin
-rwxr-xr-x 1 root root         5 сеп 16 08:48 version
-rwxr-xr-x 1 root root       107 сеп 16 08:48 vk_swiftshader_icd.json

need chmod 4755  /opt/megacubo/chrome-sandbox on install script

**Comment by EdenwareApps** [comment]
@basimamata Thanks for pointing out the issue. I added this command to the setup files starting from [release 17.5.1](https://github.com/EdenwareApps/Megacubo/releases/tag/v17.5.1).
